/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#becab9",
        "secondary": "#006e1c",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#94f990",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-dim": "#d8dadc",
        "tertiary-fixed": "#ffd9e2",
        "secondary-fixed-dim": "#bcc7de",
        "background": "#f7f9fb",
        "on-primary-fixed": "#002204",
        "on-secondary": "#ffffff",
        "surface-tint": "#006e1c",
        "inverse-primary": "#78dc77",
        "tertiary-container": "#f26f9d",
        "primary-container": "#4caf50",
        "secondary-fixed": "#d8e3fb",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#690034",
        "surface-container-low": "#f2f4f6",
        "tertiary": "#a63360",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#3e001c",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#78dc77",
        "outline": "#6f7a6b",
        "on-secondary-fixed": "#111c2d",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb1c7",
        "on-primary-fixed-variant": "#005313",
        "primary": "#006e1c",
        "on-secondary-fixed-variant": "#3c475a",
        "on-tertiary-fixed-variant": "#861948",
        "on-surface-variant": "#3f4a3c",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#586377",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#d5e0f8",
        "on-primary-container": "#003c0b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-lg": "80px",
        "stack-md": "32px",
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "stack-sm": "12px",
      },
      fontFamily: {
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Work Sans", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
